### ISSUE TITLE
Creation of RemoteDeviceEEPA53808CMD02

### ISSUE THREAD

**Issue by mccare** [aleon-GmbH/aleoncean-openhab-binding#10]
Hi,

since my Eltako Dimmer will send A5 38 08 messages after the light has changed, I would like to listen to those and update a Dimmer. I've tried to add the RemoteDeviceEEPA53808CMD02.java (similar to the LocalDevice) and added the mapping to the SupportedDevice. My item definition is here:
Switch DIMMER_DIM_03_B "XXX" {aleoncean="REMOTEID=00:86:E8:22,TYPE=RD_A5-38-08_CMD02,PARAMETER=POSITION_PERCENT,CONVPARAM=PressedUpDown"}

My problem is, that the PARAMETER is required but I cannot find the correct one. POSITION_PERCENT will lead to "No converter class found"  in DeviceContainer.itemAdd. 

What would be the correct way to achieve this?

Christian

**Comment by mccare** [comment]
Ok, I will try to use the Number and the parameter position percent. Regarding the tests, I just found a few in the library, are there more? (just to learn and adapt them)

My Eltako dimmer will act to up pressed, up released as "turn on", if you stay on "up pressed" it will dimm up. Same goes for down. If the light source changed, it will send a A5-38-08 package with the new dimm value in percent.

How would I model an Rocker Switch plus Eltako dimmer?
Define  a Number item for the Rocker Switch for "up pressed, up released, down pressed, down released". Then define a number item for the Dimmer for the A5-38-08 answer package to store the dimmed value and then use rules to map the information to a Dimmer? 

Thanks for the answer

Christian

**Comment by maggu2810** [comment]
At the time I implemented the binding there are no dimmer (at the market) that already implemented the packet sent from the actor to report the dimming value back.
Let's use an abstraction, there are two information of that actor:
* switch item: on / off
* percent value: dimming value

You could switch the device off and on and off and on without changing the dimming value.
You could also set the device to 0 percent dimming value and change the on / off without loosing the dimming value.

So, you need at all two items (IMHO): on / off + dimming value

At home I used an dimming actor (without the message reported back of the actor themselves):

```text
// Dimmaktor$
Number LIGHT_CTRL_KITCHEN_DIMMER "Dimmwert [%d]" <light> (gLight) {\
    aleoncean="LOCALID=FF:80:09:87,TYPE=LD_A5-38-08_CMD02,PARAMETER=POSITION_PERCENT"\
}
Switch LIGHT_CTRL_KITCHEN_SWITCH "an / aus [%s]" <light> (gLight) {\
    aleoncean="LOCALID=FF:80:09:87,TYPE=LD_A5-38-08_CMD02,PARAMETER=SWITCH"\
}
```

**Comment by mccare** [comment]
Ok, thanks. I've got a number value now that will update when the dimming value is updated. This is then written to a "Dimmer" Item with a rule file.
