### ISSUE TITLE
Usage of LD_A5-38-08_CMD02 to set a dimmer value

### ISSUE THREAD

**Issue by mccare** [aleon-GmbH/aleoncean-openhab-binding#11]
Hi,

how do I use a A5-38-08 CMD2 dimming local device? (LocalDeviceEEPA53808CMD02)

 I've configured a number item like:
```
    Number 	DIMMER_ELTAKO_LIVING_ROOM_COUCH_OUT "Couch Number out" 	(gGF)	{aleoncean="LOCALID=FF:FC:01:82,TYPE=LD_A5-38-08_CMD02,PARAMETER=POSITION_PERCENT"} 
```

I then use a Dimmer item and create a rule that will trigger on the change. In the rule I try to set the new number value for the DIMMER_ELTAKO_LIVING_ROOM_COUCH_OUT. 

I have tried multiple things to set the the DIMMER_ELTAKO_LIVING_ROOM_COUCH_OUT with
```
   sendCommand(DIMMER_ELTAKO_LIVING_ROOM_COUCH_OUT, 50)
```

I had to change some things:
 * in sendPacket in UserDataEEPA53808CMD02  the method getOn returned null therefore there was a NPE. How can I avoid this? Do I need to initialize some more things?
 * the dimming value was "transcoded" from 0-100 percent to 0-255 absolute in setDimmingValueRelative() in the UserData. The eltako dimmer doesn't implement the full A5-38-08 CMD2 spec, so it expects always percentage, not full values. 
* the eltako FUD61NPN dimmer doesn't like the "store value" flag, so I needed to unset it

Do you think it is an idea to link the "on" and the dimming_value? E.g. when somebody is setting the dimmer to 30, the "on" should also take place or should this be separate? Like only send the on command, when the switch is turned "on"?

Is there a way to configure or pass initial parameters to the dimming device? Or how would you make the "userData.setStoreFinalValue(true);" configurable? Or should I rather subclass and write my own device, since the eltako dimmer is not behaving to standard?

Christian
(sorry for the first question, I debugged and got now a working system)

**Comment by maggu2810** [comment]
If you edit a message, Github does not send a mail notification.
So please add a new message (or I will perhaps miss it).

The problem is, that we have to send the EEP message to the device, but don't know some stuff.

Perhaps we could state, changing the dimming value will imply state on IF the current state is not set (== null).
But if you switch the device (on or off) and the dimming value is unknown (null), is it good to imply a special on?
I don't know.

You could use rules perhaps to set a certain value.

You could try to use a openHAB persistence service and the restore last value on startup mechanism (never tried that function on OH2).

**Comment by mccare** [comment]
Yes, that might be a solution to add the "on" state if the dimming value is set to something greater than 0 and if it is not set yet.

I still don't get how the LocalEEPA53808CMD2 device should really work. My dimmer expects one packet with the percentage and the "on" flag set. From reading the code changing the "percentage" value and the "ON/off" state will each trigger one packet to be sent. My dimmer would only act to one packet, namely this with the "on" flag set and the percentage. 

So my idea would be to make this device more configurable through the item configuration (if possible)
 * pass in the flag about the "store value" flag 
 * define if the ON and dimmer values should be linked (so > 0 is ON, == 0 is OFF)

I tried to get around this by subclassing but having too many subclasses are certainly not the best idea.

Christian

**Comment by maggu2810** [comment]
The device implementation stores all values internally and sends the EEP only if both are known.

start
* on = null
* percentage = null

set percentage to 50
* on = null
* percentage = 50
* if (on != null && percentage != null) { sendEEP(on, percentage); }
* 0 message is sent

set on to true
* on = true
* percentage = 50
* if (on != null && percentage != null) { sendEEP(on, percentage); }
* 1 message is sent: on + 50

set percentage to 100
* on = true
* percentage = 100
* if (on != null && percentage != null) { sendEEP(on, percentage); }
* 1 message is sent: on + 100

set on to false
* on = false
* percentage = 100
* if (on != null && percentage != null) { sendEEP(on, percentage); }
* 1 message is sent: false + 100

**Comment by mccare** [comment]
I cannot seem to find the code values and I got a NPE when I only set the percentage. Should this check be in LocalDeviceEEPA53808CMD2?

**Comment by maggu2810** [comment]
Hm...

https://github.com/maggu2810/aleoncean/commit/f3d7e57db5930712ea364fdef10165846c547df5#diff-a9cb7c886404b10108a334308750f7a5R71

The exceptions (wrong range, no value [null]) are catched (!) and no data is sent.

**Comment by mccare** [comment]
Ah, ok, I wondered why the NPE was just "swallowed". 

Starting to understand the code :-). 

Btw, the setDimmingValueRelative has what semantics? The Eltako dimmer would like to have the percentage value there (0-100). Do I read it correctly that the percentage value is transformed into a 0-255 value?

**Comment by maggu2810** [comment]
See page 89f of https://www.enocean.com/fileadmin/redaktion/enocean_alliance/pdf/EnOcean_Equipment_Profiles_EEP_V2.6.2_public.pdf

Shortcut: EDIM
* absolute, valid range = [0;255], scale =  [0;100], Unit = %
* relative, valid range = [0;255], scale =  [0;255], Unit = s

Why I have to use relative value scaling and set EDIM_R to absolute... I don't know. ;)
Absolute will mean, that 255 = 100%
Perhaps the actors I used needs absolute, but 100% has to be 100...

I do not remember

**Comment by mccare** [comment]
Probably. I don't really know a good way how to configure this besides subclassing for a specific actor. There is no way the device can know when to use absolute or relative scaling, to use the "store value" param or not.

Btw, is there a way to send teachIn packets via the Remote device?

**Comment by mccare** [comment]
Ok, functionality is now clearer, from my side I'll close this issue (since it was more discussion anyway).

**Comment by maggu2810** [comment]
> Btw, is there a way to send teachIn packets via the Remote device?

I need to have a look at the sources.

> since it was more discussion anyway

Perhaps you could contact me directly.
