### ISSUE TITLE
Support for Contact Sensor (D5-00-01)

### ISSUE THREAD

**Issue by denniseffing** [aleon-GmbH/aleoncean-openhab-binding#16]
Hi,

I just noticed that the actual binding doesn't support the contact sensor but the base aleoncean EnOcean API does support D5-00-01. Are there any plans for supporting it or can you give me a hint where to start if I wanted to implement it myself?

Regards,
Dennis

**Comment by maggu2810** [comment]
Hi,

I cannot test it here, but I would expect if the used aleoncean artifact
does support it, the binding will support it,too.
The binding is using the device factory that uses the "SupportedDevice"
class.
https://github.com/aleon-GmbH/aleoncean/blob/master/src/main/java/eu/aleon/aleoncean/device/SupportedDevice.java#L59

Best regards,
Markus

**Comment by denniseffing** [comment]
Hi,

thanks for your response.
I tried adding the contact sensor as item to openHAB with OPEN_CLOSED as parameter as specified here: https://github.com/aleon-GmbH/aleoncean/blob/master/doc/eep/supported.md
I get the following warning in the openHAB log when the aleoncean binding updates the bindings of the items:

`[WARN ] [ean.internal.devices.DeviceContainer] - No converter class found! item type: class org.openhab.core.library.items.SwitchItem, parameter: OPEN_CLOSED, device class: class eu.aleon.aleoncean.device.remote.RemoteDeviceEEPD50001
`

So as far as I see it, the binding doesn't support it yet, even though the aleoncean artifact does.

Best regards,
Dennis

**Comment by maggu2810** [comment]
You should use a contact item, not a switch item.

A converter for the contact item should be available:
https://github.com/aleon-GmbH/aleoncean-openhab-binding/blob/master/src/main/java/org/openhab/binding/aleoncean/internal/converter/paramcitemc/OpenClosedContactItem.java

**Comment by denniseffing** [comment]
You are right, the warning comes from using a switch item instead of contact item.
I remember changing it to switch because contact didn't work at first but weirdly enough, it magically works now. I guess I must have made another mistake back then.

I will close this issue now and send a pull request soon for updating the documentation.
Thanks for your help!

Best regards,
Dennis

**Comment by maggu2810** [comment]
> I will close this issue now and send a pull request soon for updating the documentation.

Great, thank you.

Have fun.
