### ISSUE TITLE
Repository server not reachable

### ISSUE THREAD

**Issue by digitalhoax** [aleon-GmbH/aleoncean-openhab-binding#6]
Hi,

When adding this project to my openhab workspace I get errors as the maven repository in the pom.xml is unreachable (albs.aleon.eu:8082).

Is this a temporary issue or does the pom.xml need to be adjusted to solve this?

Thanks a lot!

**Comment by maggu2810** [comment]
The refered repo is not a public one.
You have to provide the aleoncean jar (not thr binding the plain logic; see the aleonceon repo) yourself.

**Comment by jrcourtois** [comment]
Don't know if it is same issue, but I don't manage to mvn install the project.

[INFO] ------------------------------------------------------------------------
[INFO] Building openHAB aleoncean Binding 1.7.3
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for eu.aleon:aleoncean:jar:1.8 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.428s
[INFO] Finished at: Tue Oct 06 11:10:35 CEST 2015
[INFO] Final Memory: 7M/156M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project org.openhab.binding.aleoncean: Could not resolve dependencies for project org.openhab.binding:org.openhab.binding.aleoncean:bundle:1.7.3: Failure to find eu.aleon:aleoncean:jar:1.8 in http://oss.jfrog.org/artifactory/libs-snapshot was cached in the local repository, resolution will not be reattempted until the update interval of openhab.repository.snapshot has elapsed or updates are forced -> [Help 1]

**Comment by maggu2810** [comment]
This is different.
All references are removed.
The bundle just uses the lib as dependency. You have to clone and build the library (referenced version), too.

**Comment by jrcourtois** [comment]
OK, I manage to build it : 
I clone the 2 projects ([binding](https://github.com/aleon-GmbH/aleoncean-openhab-binding) and [lib](https://github.com/aleon-GmbH/aleoncean)) and mvn install them.

I got an issue with the version, the 1.9 lib is generated, and the 1.8 is needed for the binding.

**Comment by maggu2810** [comment]
The current master of the library is the development status and using 1.9-SNAPSHOT.
The openHAB binding (development status) is using the latest release of the library, the version 1.8.

The library and the binding also using tags for the releases, so you could build the library version 1.8, ... using the snapshot library ...

I do not provide any builds / releases myself, as for a legal usage (IMHO) you need to be an EnOcean Alliance member.

**Comment by maggu2810** [comment]
All fine?
